AllCops:
  NewCops: enable

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Max: 80

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always
