#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'lib'

def solve(input)
  floor = 0

  input.each_char.with_index do |char, index|
    floor += (char == '(' ? 1 : -1)

    return index + 1 if floor.negative?
  end
end

test('real', expected: 1797, actual: solve(get_input('01.txt', raw: true)))

benchmark { solve(get_input('01.txt', raw: true)) }
