#!/usr/bin/env ruby
# frozen_string_literal: true

require 'digest'
require_relative 'lib'

def solve(input)
  number = 0

  loop do
    return number if Digest::MD5.hexdigest("#{input}#{number}")
      .start_with?('00000')

    number += 1
  end
end

test_multiple(
  [
    ['example 1', {
      expected: 609_043,
      actual: solve('abcdef'),
    }],
    ['example 2', {
      expected: 1_048_970,
      actual: solve('pqrstuv'),
    }],
    ['real', {
      expected: 117_946,
      actual: solve(get_input('04.txt', raw: true)),
    }],
  ],
)

benchmark { solve(get_input('04.txt', raw: true)) }
