#!/usr/bin/env lua

local input = io.open("../advent-of-code-assets/2015/input/01", "r"):read("*a")

local level = 0
local position = 0

while level >= 0 do
  position = position + 1

  if input:sub(position, position) == ")" then
    level = level - 1
  else
    level = level + 1
  end
end

-- 1797
print(position)
