#!/usr/bin/env zsh

source .env

if [[ -z "${ASSETS_REPO}" ]]; then
  echo 'Error: assets repo not set in .env'
  exit 1
fi

if [[ $# -ne 2 ]]; then
  echo 'Usage: script/browse year day'
  exit 1
fi

year="${1}"
day="${2}"

if [[ "${day}" -lt 10 ]]; then
  zero_padded_day="0${day}"
else
  zero_padded_day="${day}"
fi

script_folder=$(dirname "${0}")
prompt_filepath="${ASSETS_REPO}/${year}/prompts/${zero_padded_day}.html"

cat "${prompt_filepath}" \
  | npx html-minifier --collapse-whitespace --remove-tag-whitespace \
  | pandoc --from=html-native_divs-native_spans --to=markdown_strict+backtick_code_blocks --lua-filter="${script_folder}/code_block.lua" --wrap=none \
  | sed -r \
      -e 's/ ([.,:;!?])/\1/g' \
      -e 's/ (s[^a-z])/\1/g' \
      -e 's/\( /\(/g' \
      -e 's/ \)/\)/g' \
      -e 's/([^ ]-) ([`*])/\1\2/g' \
      -e 's/([`*]) (-[^ ])/\1\2/g' \
      -e 's/\*`([^`]+)`\*/`\1`/g' \
      -e 's/ ``//g' \
      -e 's/`` //g' \
  | glow -p -s "${script_folder}/glow.json"
