#!/usr/bin/env zsh

source .env

if [[ -z "${ASSETS_REPO}" ]]; then
  echo 'Error: assets repo not set in .env'
  exit 1
fi

if [[ -n "$(git -C "${ASSETS_REPO}" status --porcelain)" ]]; then
  echo 'Warning: assets repo has uncommitted changes'
elif ! git -C "${ASSETS_REPO}" diff "@{upstream}" --quiet; then
  echo 'Warning: assets repo has unpushed changes'
fi

if [[ $# -ne 2 ]]; then
  echo 'Usage: script/start year day'
  exit 1
fi

year=$1
day=$2

if [[ "${day}" -lt 10 ]]; then
  zero_padded_day="0${day}"
else
  zero_padded_day="${day}"
fi

script_folder=$(dirname "${0}")

"${script_folder}/download" "${year}" "${day}" || exit 1

script_path_2025="${year}/solutions/ruby/${zero_padded_day}"
part_one_script_path_2025="${script_path_2025}_1"
part_two_script_path_2025="${script_path_2025}_2"
part_one_suggestion="
$ vim ${part_one_script_path_2025} ../advent-of-code-assets/2025/input/${zero_padded_day}_example.txt
$ script/run_with_reload ${part_one_script_path_2025}
"
part_two_suggestion="
$ vim ${part_two_script_path_2025} ../advent-of-code-assets/2025/input/${zero_padded_day}_example.txt
$ script/run_with_reload ${part_two_script_path_2025}
"

if [[ ! -f "${part_one_script_path_2025}" ]]; then
  touch "${part_one_script_path_2025}"
  chmod +x "${part_one_script_path_2025}"
  echo "${part_one_suggestion}"
elif [[ ! -f "${part_two_script_path_2025}" ]]; then
  cp "${part_one_script_path_2025}" "${part_two_script_path_2025}"
  echo "${part_two_suggestion}"
else
  echo "part one${part_one_suggestion}
part_two${part_two_suggestion}"
fi

read -r '?Press enter to continue ' && \
  "${script_folder}/browse" "${year}" "${day}"
