#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'lib'

CODE_TO_SELECTION = {
  'A' => 'R',
  'B' => 'P',
  'C' => 'S',
  'X' => 'R',
  'Y' => 'P',
  'Z' => 'S',
}.freeze

def outcome_score(own_selection, opponent_selection)
  return 3 if own_selection == opponent_selection

  case [own_selection, opponent_selection]
  when %w[R S], %w[P R], %w[S P]
    6
  else
    0
  end
end

def selection_score(selection)
  {
    'R' => 1,
    'P' => 2,
    'S' => 3,
  }[selection]
end

def solve(input)
  input.reduce(0) do |total_score, round|
    opponent_selection, own_selection = round.scan(/\w/).map do |code|
      CODE_TO_SELECTION[code]
    end
    total_score += selection_score(own_selection)
    total_score + outcome_score(own_selection, opponent_selection)
  end
end

test_multiple(
  [
    ['example', {
      expected: 15,
      actual: solve(get_input('02_example.txt')),
    }],
    ['real', {
      expected: 14_297,
      actual: solve(get_input('02.txt')),
    }],
  ],
)

benchmark { solve(get_input('02.txt')) }
