#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'lib'

def solve(input)
  input.count do |pair|
    sections_by_elf = pair
      .split(',')
      .map do |sections_for_elf|
        first, last = sections_for_elf.split('-').map(&:to_i)
        { first:, last: }
      end
    sections_by_elf_sorted_by_boundary = sections_by_elf
      .sort_by { [it[:first], -it[:last]] }

    sections_by_elf_sorted_by_boundary.dig(0, :last) >=
      sections_by_elf_sorted_by_boundary.dig(1, :last)
  end
end

test_multiple(
  [
    ['less,less', {
      expected: 0,
      actual: solve(['1-2,2-3']),
    }],
    ['less,equal', {
      expected: 1,
      actual: solve(['1-2,2-2']),
    }],
    ['less,greater', {
      expected: 1,
      actual: solve(['1-3,2-2']),
    }],
    ['equal,less', {
      expected: 1,
      actual: solve(['2-2,2-3']),
    }],
    ['equal,equal', {
      expected: 1,
      actual: solve(['2-2,2-2']),
    }],
    ['equal,greater', {
      expected: 1,
      actual: solve(['2-3,2-2']),
    }],
    ['greater,less', {
      expected: 1,
      actual: solve(['3-3,2-4']),
    }],
    ['greater,equal', {
      expected: 1,
      actual: solve(['3-3,2-3']),
    }],
    ['greater,greater', {
      expected: 0,
      actual: solve(['3-3,2-2']),
    }],
    ['example', {
      expected: 2,
      actual: solve(get_input('04_example.txt')),
    }],
    ['real', {
      expected: 513,
      actual: solve(get_input('04.txt')),
    }],
  ],
)

benchmark { solve(get_input('04.txt')) }
